<a href="https://colab.research.google.com/github/alibyte/warehouse/blob/master/Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Olsen Final Intro to Python


Assignment 1

In [5]:
val = str(input("please input a string:"))

def printString(val):
    return val

print(printString(val))

please input a string:hello world!
hello world!


Assignment 2


In [14]:
def findEvens():
  total = 0
  for x in range(1,1001):
    if x%2 == 0:
      total=total+x
  return(total)
print(findEvens())

250500


Assignment 3

In [21]:
numlist = [12, 10, 3, 2, [6, [7, 8, 9], 19, 21], 21]

def findProduct(digit):
  prod = 1
  for x in digit:
    if (type(x) == type([])):
      prod = prod * findProduct(x)
    else:
      prod = prod * x
  return prod

findProduct(numlist)

18243429120

Assignment 4

In [0]:
import numpy as np

mat=[[23,43,12],[32,12,52],[15,35,52],[19,28,56]]

def matTransform(mat):
  matarray = np.array(mat)
  matarray[matarray >20]=0

  with open("final.txt","w") as outputfile:
    for finished in matarray:
      str(finished)
      outputfile.writelines(f'{finished}\n')
matTransform(mat)

#output of above:

#[ 0  0 12]
#[ 0 12  0]
#[15  0  0]
#[19  0  0]


Assignment 5

In [15]:
numList=[1,3,2,4,2,3,2,2,3,2,2,4,2,32,3,2,4,2,3,5,3,2,4,2,2,4,2,2,4,2,2,3,1,3,2,3]

def frequency(numList):
  tempdict={}
  for x in range(len(numList)):
    tempdict[numList[x]] = numList.count(numList[x])
  for k, value in tempdict.items():
    print(k,value)

frequency(numList)

1 2
3 9
2 17
4 6
32 1
5 1


Assignment 6

In [23]:


class Point:
  def __str__(self):
    return "({0},{1})".format(self.x, self.y)

  def __init__(self,x=0,y=0):
    self.x=x
    self.y=y
  
  def pointInit(self,p1,p2):
    x=p1.x+p2.x
    y=p1.y+p2.y
    return(x,y)


testPoint1 = Point(1,3)
testPoint2 = Point(3,4)

print("Point location: ", Point().pointInit(testPoint1,testPoint2))



Point location:  (4, 7)


Assignment 7

In [0]:
import pandas as pd
import datetime


def tally(reading=True):
    excelFile = "catering_sale_all.xls"
    fileRead = pd.read_excel(excelFile)
    types = []

    for x in fileRead:
        types.append(x)

    selection = []

    while reading == True:
        print("0 to exit")
        for x in selection:
            selection.remove(x)
        for x in range(1, 11):
            print(x, types[x])
        ui = int(input("Enter food ID: "))
        if ui == 0:
            reading = False
        else:
            for x in types:
                if types.index(x) == ui:
                    selection.append(x)
            tally = fileRead[selection].sum()
            print("Total: ", tally)
        return


tally()

#output:
#0 to exit
#1 chicken feet
#2 steamed dumplings
#3 ribs
#4 full chicken
#5 stuffed bun
#6 flowering cabbage
#7 doufu
#8 chive dumplings
#9 pudding
#10 original cabbage
#Enter food ID: 3
#Total:  ribs    280
#dtype: int64

Assignment 8

In [0]:
import pymysql

def conn():
  db = pymysql.connect(host='localhost',
                       user='root',
                       password='alpine',
                       db='db')
  return db

def lifeAvg(db):
  cur=db.cursor()
  sql = "Select AVG(LifeExpectancy),Continent FROM Country GROUP BY Continent"
  cur.execute(sql)
  dump=cur.fetchall()
  print("Average Life : Continent")
  for x in list(dump):
    print(x[0]," : ",x[1])

db = conn()
lifeAvg(db)

Assignment 9

In [0]:
import pymysql, matplotlib.pyplot

#luckily a lot can be copied over from the previous assignment.

def conn():
  db = pymysql.connect(host='localhost',
                       user='root',
                       password='alpine',
                       db='db')
  return db

def popTotal(db):
  cur=db.cursor()
  sql = "Select SUM(Population),Continent FROM Country GROUP BY Continent"
  cur.execute(sql)
  dump=cur.fetchall()

  fig(1,figsize=(6,6))

  pop=[]
  loc=[]

  for x in dump:
    pop.append(x[0])
    loc.append(x[1])


  pie(portion,explode=0.1,labels=(Continent,Population))
  title("Pop by Continent")
  
  return pyplot.show()

  db = conn()
  popTotal(db)

Assignment 10

In [0]:
import pandas as pd
import matplotlib.pyplot

def fileRead(year):
  dump = pd.read_csv("energy-production.csv")
  Row = dump[dump['Year']==year]
  Row = Row.drop(columns=['Unnamed: 0','Year'],axis=1)
  y=[]
  x=[]
  for k,values in Row.items():
    for x in values:
      y.append(x)
  for i in Row:
    x.append(i)
  pyplot.bar(x,y)
  pyplot.xticks(x,ha='right')
  return pyplot.show()

year = int(input("Input a year: "))
fileRead(year)

